[[task]]
  id = "test"
  description = "Run all go tests"
  type = "short"
  cmd = "go test -v ./..."


[[task]]
  id = "schemagen"
  description = "Generate ent schema"
  type = "short"
  cmd = """
    echo "Generating ent schema..."
    go generate ent/
  """


[[task]]
  id = "newent"
  description = "Create new ent entiry"
  type = "short"
  cmd = """
    go run -mod=mod entgo.io/ent/cmd/ent new --template=template/with-common.tmpl
  """

[[task]]
  id = "migrate"
  description = "Run ent migration"
  type = "group"
  dependencies = ["ent/migrate/gen"]