[[task]]
  id = "test"
  description = "Run all go tests"
  type = "short"
  cmd = "go test -v ./..."


[[task]]
  id = "gen"
  description = "Generate everything"
  type = "short"
  watch = ["ent/schema/*.go", "ent/entc.go", "gqlgen.yml"]
  cmd = """
    echo "Running ent generation with go generate..."
    go generate
  """


[[task]]
  id = "newent"
  description = "Create new ent entity"
  type = "short"
  cmd = """
    go run -mod=mod entgo.io/ent/cmd/ent new --template=template/with-common.tmpl
  """

[[task]]
  id = "migrate"
  description = "Run ent migration"
  type = "group"
  dependencies = ["ent/migrate/gen"]

[[task]]
  id = "serve"
  description = "Run gqlserver"
  type = "long"
  triggers = ["gen"]
  cmd = "go run -mod=mod cmd/dndgen/main.go"

[[task]]
  id = "dev"
  description = "Run gqlserver in dev mode"
  type = "long"
  triggers = ["gen"]
  cmd = """
    echo "Running dev server..."
    sleep 100
  """
