[[task]]
  id = "popgen"
  description = "Generate the Popper populators"
  type = "short"
  watch = ["gen.go"]
  cmd = """
    echo "Running popper generation with go generate..."
    go run gen.go
  """