[[task]]
  id = "gen"
  type = "short"
  description = "Generate the Popper populators"
  cmd = """
    go generate
  """

[[task]]
  id = "pop"
  type = "short"
  description = "Run the Popper populators"
  cmd = """
    go run -mod=mod cmd/dndgen/main.go
  """
