[[task]]
  id = "hash"
  type = "short"
  cmd = """
  atlas migrate hash \
    --dir "file://migrations"
  """

[[task]]
  id = "diff"
  type = "short"
  cmd = """
  atlas migrate diff init \
    --dir "file://migrations" \
    --to "ent://../schema?globalid=1" \
    --dev-url "sqlite://dev?mode=memory&_fk=1"
  """

[[task]]
  id = "lint"
  type = "short"
  cmd = """
  atlas migrate lint \
    --dir "file://migrations" \
    --dev-url "sqlite://dev?mode=memory&_fk=1" \
    --latest=1
  """

[[task]]
  id = "validate"
  type = "short"
  cmd = """
  atlas migrate validate \
    --dir "file://migrations" \
    --dev-url "sqlite://dev?mode=memory&_fk=1" 
  """

[[task]]
  id = "apply"
  type = "short"
  dependencies = ["lint", "validate"]
  cmd = """
  atlas migrate apply \
    --dir "file://migrations" \
    --url "sqlite://file.db?_fk=1"
  """

[[task]]
  id = "clean"
  type = "short"
  cmd = """
  atlas schema clean \
    --url "sqlite://file.db?_fk=1" \
    --auto-approve
  """