[[task]]
  id = "man"
  type = "short"
  cmd = """
  atlas migrate new MANUAL_MIGRATION \
    --dir "file://migrations"
  """

[[task]]
  id = "hash"
  type = "short"
  cmd = """
  atlas migrate hash \
    --dir "file://migrations"
  """

[[task]]
  id = "genman"
  type = "short"
  cmd = """
  atlas migrate diff GENERATED_MIGRATION \
    --dir "file://migrations" \
    --to "ent://../schema" \
    --dev-url "sqlite://file?mode=memory&_fk=1"
  """

[[task]]
  id = "gen"
  type = "short"
  cmd = """
    go run -mod=mod main.go seed
  """

[[task]]
  id = "apply"
  type = "short"
  cmd = """
  atlas migrate apply \
    --dir "file://migrations" \
    --url "sqlite://file.db?_fk=1"
  """