// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ecshreve/dndgen/ent/equipmentchoice"
	"github.com/ecshreve/dndgen/ent/predicate"
)

// EquipmentChoiceDelete is the builder for deleting a EquipmentChoice entity.
type EquipmentChoiceDelete struct {
	config
	hooks    []Hook
	mutation *EquipmentChoiceMutation
}

// Where appends a list predicates to the EquipmentChoiceDelete builder.
func (ecd *EquipmentChoiceDelete) Where(ps ...predicate.EquipmentChoice) *EquipmentChoiceDelete {
	ecd.mutation.Where(ps...)
	return ecd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ecd *EquipmentChoiceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ecd.sqlExec, ecd.mutation, ecd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ecd *EquipmentChoiceDelete) ExecX(ctx context.Context) int {
	n, err := ecd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ecd *EquipmentChoiceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(equipmentchoice.Table, sqlgraph.NewFieldSpec(equipmentchoice.FieldID, field.TypeInt))
	if ps := ecd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ecd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ecd.mutation.done = true
	return affected, err
}

// EquipmentChoiceDeleteOne is the builder for deleting a single EquipmentChoice entity.
type EquipmentChoiceDeleteOne struct {
	ecd *EquipmentChoiceDelete
}

// Where appends a list predicates to the EquipmentChoiceDelete builder.
func (ecdo *EquipmentChoiceDeleteOne) Where(ps ...predicate.EquipmentChoice) *EquipmentChoiceDeleteOne {
	ecdo.ecd.mutation.Where(ps...)
	return ecdo
}

// Exec executes the deletion query.
func (ecdo *EquipmentChoiceDeleteOne) Exec(ctx context.Context) error {
	n, err := ecdo.ecd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{equipmentchoice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ecdo *EquipmentChoiceDeleteOne) ExecX(ctx context.Context) {
	if err := ecdo.Exec(ctx); err != nil {
		panic(err)
	}
}
