// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ecshreve/dndgen/ent/abilitybonus"
	"github.com/ecshreve/dndgen/ent/predicate"
)

// AbilityBonusDelete is the builder for deleting a AbilityBonus entity.
type AbilityBonusDelete struct {
	config
	hooks    []Hook
	mutation *AbilityBonusMutation
}

// Where appends a list predicates to the AbilityBonusDelete builder.
func (abd *AbilityBonusDelete) Where(ps ...predicate.AbilityBonus) *AbilityBonusDelete {
	abd.mutation.Where(ps...)
	return abd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (abd *AbilityBonusDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, abd.sqlExec, abd.mutation, abd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (abd *AbilityBonusDelete) ExecX(ctx context.Context) int {
	n, err := abd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (abd *AbilityBonusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(abilitybonus.Table, sqlgraph.NewFieldSpec(abilitybonus.FieldID, field.TypeInt))
	if ps := abd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, abd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	abd.mutation.done = true
	return affected, err
}

// AbilityBonusDeleteOne is the builder for deleting a single AbilityBonus entity.
type AbilityBonusDeleteOne struct {
	abd *AbilityBonusDelete
}

// Where appends a list predicates to the AbilityBonusDelete builder.
func (abdo *AbilityBonusDeleteOne) Where(ps ...predicate.AbilityBonus) *AbilityBonusDeleteOne {
	abdo.abd.mutation.Where(ps...)
	return abdo
}

// Exec executes the deletion query.
func (abdo *AbilityBonusDeleteOne) Exec(ctx context.Context) error {
	n, err := abdo.abd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{abilitybonus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (abdo *AbilityBonusDeleteOne) ExecX(ctx context.Context) {
	if err := abdo.Exec(ctx); err != nil {
		panic(err)
	}
}
