// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ecshreve/dndgen/ent/language"
	"github.com/ecshreve/dndgen/ent/predicate"
	"github.com/ecshreve/dndgen/ent/race"
)

// LanguageUpdate is the builder for updating Language entities.
type LanguageUpdate struct {
	config
	hooks    []Hook
	mutation *LanguageMutation
}

// Where appends a list predicates to the LanguageUpdate builder.
func (lu *LanguageUpdate) Where(ps ...predicate.Language) *LanguageUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetIndx sets the "indx" field.
func (lu *LanguageUpdate) SetIndx(s string) *LanguageUpdate {
	lu.mutation.SetIndx(s)
	return lu
}

// SetName sets the "name" field.
func (lu *LanguageUpdate) SetName(s string) *LanguageUpdate {
	lu.mutation.SetName(s)
	return lu
}

// SetDesc sets the "desc" field.
func (lu *LanguageUpdate) SetDesc(s string) *LanguageUpdate {
	lu.mutation.SetDesc(s)
	return lu
}

// SetCategory sets the "category" field.
func (lu *LanguageUpdate) SetCategory(l language.Category) *LanguageUpdate {
	lu.mutation.SetCategory(l)
	return lu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (lu *LanguageUpdate) SetNillableCategory(l *language.Category) *LanguageUpdate {
	if l != nil {
		lu.SetCategory(*l)
	}
	return lu
}

// SetScript sets the "script" field.
func (lu *LanguageUpdate) SetScript(s string) *LanguageUpdate {
	lu.mutation.SetScript(s)
	return lu
}

// AddSpeakerIDs adds the "speakers" edge to the Race entity by IDs.
func (lu *LanguageUpdate) AddSpeakerIDs(ids ...int) *LanguageUpdate {
	lu.mutation.AddSpeakerIDs(ids...)
	return lu
}

// AddSpeakers adds the "speakers" edges to the Race entity.
func (lu *LanguageUpdate) AddSpeakers(r ...*Race) *LanguageUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return lu.AddSpeakerIDs(ids...)
}

// Mutation returns the LanguageMutation object of the builder.
func (lu *LanguageUpdate) Mutation() *LanguageMutation {
	return lu.mutation
}

// ClearSpeakers clears all "speakers" edges to the Race entity.
func (lu *LanguageUpdate) ClearSpeakers() *LanguageUpdate {
	lu.mutation.ClearSpeakers()
	return lu
}

// RemoveSpeakerIDs removes the "speakers" edge to Race entities by IDs.
func (lu *LanguageUpdate) RemoveSpeakerIDs(ids ...int) *LanguageUpdate {
	lu.mutation.RemoveSpeakerIDs(ids...)
	return lu
}

// RemoveSpeakers removes "speakers" edges to Race entities.
func (lu *LanguageUpdate) RemoveSpeakers(r ...*Race) *LanguageUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return lu.RemoveSpeakerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LanguageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, LanguageMutation](ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LanguageUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LanguageUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LanguageUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LanguageUpdate) check() error {
	if v, ok := lu.mutation.Category(); ok {
		if err := language.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Language.category": %w`, err)}
		}
	}
	return nil
}

func (lu *LanguageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(language.Table, language.Columns, sqlgraph.NewFieldSpec(language.FieldID, field.TypeInt))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Indx(); ok {
		_spec.SetField(language.FieldIndx, field.TypeString, value)
	}
	if value, ok := lu.mutation.Name(); ok {
		_spec.SetField(language.FieldName, field.TypeString, value)
	}
	if value, ok := lu.mutation.Desc(); ok {
		_spec.SetField(language.FieldDesc, field.TypeString, value)
	}
	if value, ok := lu.mutation.Category(); ok {
		_spec.SetField(language.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := lu.mutation.Script(); ok {
		_spec.SetField(language.FieldScript, field.TypeString, value)
	}
	if lu.mutation.SpeakersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   language.SpeakersTable,
			Columns: language.SpeakersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(race.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedSpeakersIDs(); len(nodes) > 0 && !lu.mutation.SpeakersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   language.SpeakersTable,
			Columns: language.SpeakersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(race.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.SpeakersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   language.SpeakersTable,
			Columns: language.SpeakersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(race.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{language.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LanguageUpdateOne is the builder for updating a single Language entity.
type LanguageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LanguageMutation
}

// SetIndx sets the "indx" field.
func (luo *LanguageUpdateOne) SetIndx(s string) *LanguageUpdateOne {
	luo.mutation.SetIndx(s)
	return luo
}

// SetName sets the "name" field.
func (luo *LanguageUpdateOne) SetName(s string) *LanguageUpdateOne {
	luo.mutation.SetName(s)
	return luo
}

// SetDesc sets the "desc" field.
func (luo *LanguageUpdateOne) SetDesc(s string) *LanguageUpdateOne {
	luo.mutation.SetDesc(s)
	return luo
}

// SetCategory sets the "category" field.
func (luo *LanguageUpdateOne) SetCategory(l language.Category) *LanguageUpdateOne {
	luo.mutation.SetCategory(l)
	return luo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (luo *LanguageUpdateOne) SetNillableCategory(l *language.Category) *LanguageUpdateOne {
	if l != nil {
		luo.SetCategory(*l)
	}
	return luo
}

// SetScript sets the "script" field.
func (luo *LanguageUpdateOne) SetScript(s string) *LanguageUpdateOne {
	luo.mutation.SetScript(s)
	return luo
}

// AddSpeakerIDs adds the "speakers" edge to the Race entity by IDs.
func (luo *LanguageUpdateOne) AddSpeakerIDs(ids ...int) *LanguageUpdateOne {
	luo.mutation.AddSpeakerIDs(ids...)
	return luo
}

// AddSpeakers adds the "speakers" edges to the Race entity.
func (luo *LanguageUpdateOne) AddSpeakers(r ...*Race) *LanguageUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return luo.AddSpeakerIDs(ids...)
}

// Mutation returns the LanguageMutation object of the builder.
func (luo *LanguageUpdateOne) Mutation() *LanguageMutation {
	return luo.mutation
}

// ClearSpeakers clears all "speakers" edges to the Race entity.
func (luo *LanguageUpdateOne) ClearSpeakers() *LanguageUpdateOne {
	luo.mutation.ClearSpeakers()
	return luo
}

// RemoveSpeakerIDs removes the "speakers" edge to Race entities by IDs.
func (luo *LanguageUpdateOne) RemoveSpeakerIDs(ids ...int) *LanguageUpdateOne {
	luo.mutation.RemoveSpeakerIDs(ids...)
	return luo
}

// RemoveSpeakers removes "speakers" edges to Race entities.
func (luo *LanguageUpdateOne) RemoveSpeakers(r ...*Race) *LanguageUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return luo.RemoveSpeakerIDs(ids...)
}

// Where appends a list predicates to the LanguageUpdate builder.
func (luo *LanguageUpdateOne) Where(ps ...predicate.Language) *LanguageUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LanguageUpdateOne) Select(field string, fields ...string) *LanguageUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Language entity.
func (luo *LanguageUpdateOne) Save(ctx context.Context) (*Language, error) {
	return withHooks[*Language, LanguageMutation](ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LanguageUpdateOne) SaveX(ctx context.Context) *Language {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LanguageUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LanguageUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LanguageUpdateOne) check() error {
	if v, ok := luo.mutation.Category(); ok {
		if err := language.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Language.category": %w`, err)}
		}
	}
	return nil
}

func (luo *LanguageUpdateOne) sqlSave(ctx context.Context) (_node *Language, err error) {
	if err := luo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(language.Table, language.Columns, sqlgraph.NewFieldSpec(language.FieldID, field.TypeInt))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Language.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, language.FieldID)
		for _, f := range fields {
			if !language.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != language.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Indx(); ok {
		_spec.SetField(language.FieldIndx, field.TypeString, value)
	}
	if value, ok := luo.mutation.Name(); ok {
		_spec.SetField(language.FieldName, field.TypeString, value)
	}
	if value, ok := luo.mutation.Desc(); ok {
		_spec.SetField(language.FieldDesc, field.TypeString, value)
	}
	if value, ok := luo.mutation.Category(); ok {
		_spec.SetField(language.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := luo.mutation.Script(); ok {
		_spec.SetField(language.FieldScript, field.TypeString, value)
	}
	if luo.mutation.SpeakersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   language.SpeakersTable,
			Columns: language.SpeakersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(race.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedSpeakersIDs(); len(nodes) > 0 && !luo.mutation.SpeakersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   language.SpeakersTable,
			Columns: language.SpeakersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(race.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.SpeakersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   language.SpeakersTable,
			Columns: language.SpeakersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(race.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Language{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{language.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
