// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ecshreve/dndgen/ent/race"
)

// Race is the model entity for the Race schema.
type Race struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Indx holds the value of the "indx" field.
	Indx string `json:"index"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Speed holds the value of the "speed" field.
	Speed int `json:"speed,omitempty"`
	// Size holds the value of the "size" field.
	Size race.Size `json:"size,omitempty"`
	// SizeDesc holds the value of the "size_desc" field.
	SizeDesc string `json:"size_description"`
	// AlignmentDesc holds the value of the "alignment_desc" field.
	AlignmentDesc string `json:"alignment"`
	// AgeDesc holds the value of the "age_desc" field.
	AgeDesc string `json:"age"`
	// LanguageDesc holds the value of the "language_desc" field.
	LanguageDesc string `json:"language_desc,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Race) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case race.FieldID, race.FieldSpeed:
			values[i] = new(sql.NullInt64)
		case race.FieldIndx, race.FieldName, race.FieldSize, race.FieldSizeDesc, race.FieldAlignmentDesc, race.FieldAgeDesc, race.FieldLanguageDesc:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Race fields.
func (r *Race) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case race.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case race.FieldIndx:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field indx", values[i])
			} else if value.Valid {
				r.Indx = value.String
			}
		case race.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				r.Name = value.String
			}
		case race.FieldSpeed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field speed", values[i])
			} else if value.Valid {
				r.Speed = int(value.Int64)
			}
		case race.FieldSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				r.Size = race.Size(value.String)
			}
		case race.FieldSizeDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size_desc", values[i])
			} else if value.Valid {
				r.SizeDesc = value.String
			}
		case race.FieldAlignmentDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alignment_desc", values[i])
			} else if value.Valid {
				r.AlignmentDesc = value.String
			}
		case race.FieldAgeDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field age_desc", values[i])
			} else if value.Valid {
				r.AgeDesc = value.String
			}
		case race.FieldLanguageDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language_desc", values[i])
			} else if value.Valid {
				r.LanguageDesc = value.String
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Race.
// This includes values selected through modifiers, order, etc.
func (r *Race) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// Update returns a builder for updating this Race.
// Note that you need to call Race.Unwrap() before calling this method if this Race
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Race) Update() *RaceUpdateOne {
	return NewRaceClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Race entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Race) Unwrap() *Race {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Race is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Race) String() string {
	var builder strings.Builder
	builder.WriteString("Race(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("indx=")
	builder.WriteString(r.Indx)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(r.Name)
	builder.WriteString(", ")
	builder.WriteString("speed=")
	builder.WriteString(fmt.Sprintf("%v", r.Speed))
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", r.Size))
	builder.WriteString(", ")
	builder.WriteString("size_desc=")
	builder.WriteString(r.SizeDesc)
	builder.WriteString(", ")
	builder.WriteString("alignment_desc=")
	builder.WriteString(r.AlignmentDesc)
	builder.WriteString(", ")
	builder.WriteString("age_desc=")
	builder.WriteString(r.AgeDesc)
	builder.WriteString(", ")
	builder.WriteString("language_desc=")
	builder.WriteString(r.LanguageDesc)
	builder.WriteByte(')')
	return builder.String()
}

func (rc *RaceCreate) SetRace(input *Race) *RaceCreate {
	rc.SetIndx(input.Indx)
	rc.SetName(input.Name)
	rc.SetSpeed(input.Speed)
	rc.SetSize(input.Size)
	rc.SetSizeDesc(input.SizeDesc)
	rc.SetAlignmentDesc(input.AlignmentDesc)
	rc.SetAgeDesc(input.AgeDesc)
	rc.SetLanguageDesc(input.LanguageDesc)
	return rc
}

// Races is a parsable slice of Race.
type Races []*Race
