// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ecshreve/dndgen/ent/rule"
	"github.com/ecshreve/dndgen/ent/rulesection"
)

// RuleSectionCreate is the builder for creating a RuleSection entity.
type RuleSectionCreate struct {
	config
	mutation *RuleSectionMutation
	hooks    []Hook
}

// SetIndx sets the "indx" field.
func (rsc *RuleSectionCreate) SetIndx(s string) *RuleSectionCreate {
	rsc.mutation.SetIndx(s)
	return rsc
}

// SetName sets the "name" field.
func (rsc *RuleSectionCreate) SetName(s string) *RuleSectionCreate {
	rsc.mutation.SetName(s)
	return rsc
}

// SetDesc sets the "desc" field.
func (rsc *RuleSectionCreate) SetDesc(s string) *RuleSectionCreate {
	rsc.mutation.SetDesc(s)
	return rsc
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (rsc *RuleSectionCreate) AddRuleIDs(ids ...int) *RuleSectionCreate {
	rsc.mutation.AddRuleIDs(ids...)
	return rsc
}

// AddRules adds the "rules" edges to the Rule entity.
func (rsc *RuleSectionCreate) AddRules(r ...*Rule) *RuleSectionCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rsc.AddRuleIDs(ids...)
}

// Mutation returns the RuleSectionMutation object of the builder.
func (rsc *RuleSectionCreate) Mutation() *RuleSectionMutation {
	return rsc.mutation
}

// Save creates the RuleSection in the database.
func (rsc *RuleSectionCreate) Save(ctx context.Context) (*RuleSection, error) {
	return withHooks(ctx, rsc.sqlSave, rsc.mutation, rsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rsc *RuleSectionCreate) SaveX(ctx context.Context) *RuleSection {
	v, err := rsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rsc *RuleSectionCreate) Exec(ctx context.Context) error {
	_, err := rsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rsc *RuleSectionCreate) ExecX(ctx context.Context) {
	if err := rsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rsc *RuleSectionCreate) check() error {
	if _, ok := rsc.mutation.Indx(); !ok {
		return &ValidationError{Name: "indx", err: errors.New(`ent: missing required field "RuleSection.indx"`)}
	}
	if v, ok := rsc.mutation.Indx(); ok {
		if err := rulesection.IndxValidator(v); err != nil {
			return &ValidationError{Name: "indx", err: fmt.Errorf(`ent: validator failed for field "RuleSection.indx": %w`, err)}
		}
	}
	if _, ok := rsc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RuleSection.name"`)}
	}
	if v, ok := rsc.mutation.Name(); ok {
		if err := rulesection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RuleSection.name": %w`, err)}
		}
	}
	if _, ok := rsc.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "RuleSection.desc"`)}
	}
	return nil
}

func (rsc *RuleSectionCreate) sqlSave(ctx context.Context) (*RuleSection, error) {
	if err := rsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rsc.mutation.id = &_node.ID
	rsc.mutation.done = true
	return _node, nil
}

func (rsc *RuleSectionCreate) createSpec() (*RuleSection, *sqlgraph.CreateSpec) {
	var (
		_node = &RuleSection{config: rsc.config}
		_spec = sqlgraph.NewCreateSpec(rulesection.Table, sqlgraph.NewFieldSpec(rulesection.FieldID, field.TypeInt))
	)
	if value, ok := rsc.mutation.Indx(); ok {
		_spec.SetField(rulesection.FieldIndx, field.TypeString, value)
		_node.Indx = value
	}
	if value, ok := rsc.mutation.Name(); ok {
		_spec.SetField(rulesection.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := rsc.mutation.Desc(); ok {
		_spec.SetField(rulesection.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if nodes := rsc.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   rulesection.RulesTable,
			Columns: rulesection.RulesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RuleSectionCreateBulk is the builder for creating many RuleSection entities in bulk.
type RuleSectionCreateBulk struct {
	config
	builders []*RuleSectionCreate
}

// Save creates the RuleSection entities in the database.
func (rscb *RuleSectionCreateBulk) Save(ctx context.Context) ([]*RuleSection, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rscb.builders))
	nodes := make([]*RuleSection, len(rscb.builders))
	mutators := make([]Mutator, len(rscb.builders))
	for i := range rscb.builders {
		func(i int, root context.Context) {
			builder := rscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RuleSectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rscb *RuleSectionCreateBulk) SaveX(ctx context.Context) []*RuleSection {
	v, err := rscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rscb *RuleSectionCreateBulk) Exec(ctx context.Context) error {
	_, err := rscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rscb *RuleSectionCreateBulk) ExecX(ctx context.Context) {
	if err := rscb.Exec(ctx); err != nil {
		panic(err)
	}
}
