// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ecshreve/dndgen/ent/damage"
	"github.com/ecshreve/dndgen/ent/equipment"
	"github.com/ecshreve/dndgen/ent/predicate"
	"github.com/ecshreve/dndgen/ent/property"
	"github.com/ecshreve/dndgen/ent/weapon"
	"github.com/ecshreve/dndgen/ent/weaponrange"
)

// WeaponUpdate is the builder for updating Weapon entities.
type WeaponUpdate struct {
	config
	hooks    []Hook
	mutation *WeaponMutation
}

// Where appends a list predicates to the WeaponUpdate builder.
func (wu *WeaponUpdate) Where(ps ...predicate.Weapon) *WeaponUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetWeaponCategory sets the "weapon_category" field.
func (wu *WeaponUpdate) SetWeaponCategory(wc weapon.WeaponCategory) *WeaponUpdate {
	wu.mutation.SetWeaponCategory(wc)
	return wu
}

// SetNillableWeaponCategory sets the "weapon_category" field if the given value is not nil.
func (wu *WeaponUpdate) SetNillableWeaponCategory(wc *weapon.WeaponCategory) *WeaponUpdate {
	if wc != nil {
		wu.SetWeaponCategory(*wc)
	}
	return wu
}

// SetWeaponSubcategory sets the "weapon_subcategory" field.
func (wu *WeaponUpdate) SetWeaponSubcategory(ws weapon.WeaponSubcategory) *WeaponUpdate {
	wu.mutation.SetWeaponSubcategory(ws)
	return wu
}

// SetNillableWeaponSubcategory sets the "weapon_subcategory" field if the given value is not nil.
func (wu *WeaponUpdate) SetNillableWeaponSubcategory(ws *weapon.WeaponSubcategory) *WeaponUpdate {
	if ws != nil {
		wu.SetWeaponSubcategory(*ws)
	}
	return wu
}

// SetDamageID sets the "damage" edge to the Damage entity by ID.
func (wu *WeaponUpdate) SetDamageID(id int) *WeaponUpdate {
	wu.mutation.SetDamageID(id)
	return wu
}

// SetNillableDamageID sets the "damage" edge to the Damage entity by ID if the given value is not nil.
func (wu *WeaponUpdate) SetNillableDamageID(id *int) *WeaponUpdate {
	if id != nil {
		wu = wu.SetDamageID(*id)
	}
	return wu
}

// SetDamage sets the "damage" edge to the Damage entity.
func (wu *WeaponUpdate) SetDamage(d *Damage) *WeaponUpdate {
	return wu.SetDamageID(d.ID)
}

// AddPropertyIDs adds the "properties" edge to the Property entity by IDs.
func (wu *WeaponUpdate) AddPropertyIDs(ids ...int) *WeaponUpdate {
	wu.mutation.AddPropertyIDs(ids...)
	return wu
}

// AddProperties adds the "properties" edges to the Property entity.
func (wu *WeaponUpdate) AddProperties(p ...*Property) *WeaponUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return wu.AddPropertyIDs(ids...)
}

// SetEquipmentID sets the "equipment" edge to the Equipment entity by ID.
func (wu *WeaponUpdate) SetEquipmentID(id int) *WeaponUpdate {
	wu.mutation.SetEquipmentID(id)
	return wu
}

// SetNillableEquipmentID sets the "equipment" edge to the Equipment entity by ID if the given value is not nil.
func (wu *WeaponUpdate) SetNillableEquipmentID(id *int) *WeaponUpdate {
	if id != nil {
		wu = wu.SetEquipmentID(*id)
	}
	return wu
}

// SetEquipment sets the "equipment" edge to the Equipment entity.
func (wu *WeaponUpdate) SetEquipment(e *Equipment) *WeaponUpdate {
	return wu.SetEquipmentID(e.ID)
}

// SetWeaponRangeID sets the "weapon_range" edge to the WeaponRange entity by ID.
func (wu *WeaponUpdate) SetWeaponRangeID(id int) *WeaponUpdate {
	wu.mutation.SetWeaponRangeID(id)
	return wu
}

// SetNillableWeaponRangeID sets the "weapon_range" edge to the WeaponRange entity by ID if the given value is not nil.
func (wu *WeaponUpdate) SetNillableWeaponRangeID(id *int) *WeaponUpdate {
	if id != nil {
		wu = wu.SetWeaponRangeID(*id)
	}
	return wu
}

// SetWeaponRange sets the "weapon_range" edge to the WeaponRange entity.
func (wu *WeaponUpdate) SetWeaponRange(w *WeaponRange) *WeaponUpdate {
	return wu.SetWeaponRangeID(w.ID)
}

// Mutation returns the WeaponMutation object of the builder.
func (wu *WeaponUpdate) Mutation() *WeaponMutation {
	return wu.mutation
}

// ClearDamage clears the "damage" edge to the Damage entity.
func (wu *WeaponUpdate) ClearDamage() *WeaponUpdate {
	wu.mutation.ClearDamage()
	return wu
}

// ClearProperties clears all "properties" edges to the Property entity.
func (wu *WeaponUpdate) ClearProperties() *WeaponUpdate {
	wu.mutation.ClearProperties()
	return wu
}

// RemovePropertyIDs removes the "properties" edge to Property entities by IDs.
func (wu *WeaponUpdate) RemovePropertyIDs(ids ...int) *WeaponUpdate {
	wu.mutation.RemovePropertyIDs(ids...)
	return wu
}

// RemoveProperties removes "properties" edges to Property entities.
func (wu *WeaponUpdate) RemoveProperties(p ...*Property) *WeaponUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return wu.RemovePropertyIDs(ids...)
}

// ClearEquipment clears the "equipment" edge to the Equipment entity.
func (wu *WeaponUpdate) ClearEquipment() *WeaponUpdate {
	wu.mutation.ClearEquipment()
	return wu
}

// ClearWeaponRange clears the "weapon_range" edge to the WeaponRange entity.
func (wu *WeaponUpdate) ClearWeaponRange() *WeaponUpdate {
	wu.mutation.ClearWeaponRange()
	return wu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WeaponUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WeaponUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WeaponUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WeaponUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WeaponUpdate) check() error {
	if v, ok := wu.mutation.WeaponCategory(); ok {
		if err := weapon.WeaponCategoryValidator(v); err != nil {
			return &ValidationError{Name: "weapon_category", err: fmt.Errorf(`ent: validator failed for field "Weapon.weapon_category": %w`, err)}
		}
	}
	if v, ok := wu.mutation.WeaponSubcategory(); ok {
		if err := weapon.WeaponSubcategoryValidator(v); err != nil {
			return &ValidationError{Name: "weapon_subcategory", err: fmt.Errorf(`ent: validator failed for field "Weapon.weapon_subcategory": %w`, err)}
		}
	}
	return nil
}

func (wu *WeaponUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(weapon.Table, weapon.Columns, sqlgraph.NewFieldSpec(weapon.FieldID, field.TypeInt))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.WeaponCategory(); ok {
		_spec.SetField(weapon.FieldWeaponCategory, field.TypeEnum, value)
	}
	if value, ok := wu.mutation.WeaponSubcategory(); ok {
		_spec.SetField(weapon.FieldWeaponSubcategory, field.TypeEnum, value)
	}
	if wu.mutation.DamageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.DamageTable,
			Columns: []string{weapon.DamageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(damage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.DamageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.DamageTable,
			Columns: []string{weapon.DamageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(damage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   weapon.PropertiesTable,
			Columns: weapon.PropertiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !wu.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   weapon.PropertiesTable,
			Columns: weapon.PropertiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   weapon.PropertiesTable,
			Columns: weapon.PropertiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.EquipmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.EquipmentTable,
			Columns: []string{weapon.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(equipment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.EquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.EquipmentTable,
			Columns: []string{weapon.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(equipment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.WeaponRangeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.WeaponRangeTable,
			Columns: []string{weapon.WeaponRangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weaponrange.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.WeaponRangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.WeaponRangeTable,
			Columns: []string{weapon.WeaponRangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weaponrange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{weapon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WeaponUpdateOne is the builder for updating a single Weapon entity.
type WeaponUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WeaponMutation
}

// SetWeaponCategory sets the "weapon_category" field.
func (wuo *WeaponUpdateOne) SetWeaponCategory(wc weapon.WeaponCategory) *WeaponUpdateOne {
	wuo.mutation.SetWeaponCategory(wc)
	return wuo
}

// SetNillableWeaponCategory sets the "weapon_category" field if the given value is not nil.
func (wuo *WeaponUpdateOne) SetNillableWeaponCategory(wc *weapon.WeaponCategory) *WeaponUpdateOne {
	if wc != nil {
		wuo.SetWeaponCategory(*wc)
	}
	return wuo
}

// SetWeaponSubcategory sets the "weapon_subcategory" field.
func (wuo *WeaponUpdateOne) SetWeaponSubcategory(ws weapon.WeaponSubcategory) *WeaponUpdateOne {
	wuo.mutation.SetWeaponSubcategory(ws)
	return wuo
}

// SetNillableWeaponSubcategory sets the "weapon_subcategory" field if the given value is not nil.
func (wuo *WeaponUpdateOne) SetNillableWeaponSubcategory(ws *weapon.WeaponSubcategory) *WeaponUpdateOne {
	if ws != nil {
		wuo.SetWeaponSubcategory(*ws)
	}
	return wuo
}

// SetDamageID sets the "damage" edge to the Damage entity by ID.
func (wuo *WeaponUpdateOne) SetDamageID(id int) *WeaponUpdateOne {
	wuo.mutation.SetDamageID(id)
	return wuo
}

// SetNillableDamageID sets the "damage" edge to the Damage entity by ID if the given value is not nil.
func (wuo *WeaponUpdateOne) SetNillableDamageID(id *int) *WeaponUpdateOne {
	if id != nil {
		wuo = wuo.SetDamageID(*id)
	}
	return wuo
}

// SetDamage sets the "damage" edge to the Damage entity.
func (wuo *WeaponUpdateOne) SetDamage(d *Damage) *WeaponUpdateOne {
	return wuo.SetDamageID(d.ID)
}

// AddPropertyIDs adds the "properties" edge to the Property entity by IDs.
func (wuo *WeaponUpdateOne) AddPropertyIDs(ids ...int) *WeaponUpdateOne {
	wuo.mutation.AddPropertyIDs(ids...)
	return wuo
}

// AddProperties adds the "properties" edges to the Property entity.
func (wuo *WeaponUpdateOne) AddProperties(p ...*Property) *WeaponUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return wuo.AddPropertyIDs(ids...)
}

// SetEquipmentID sets the "equipment" edge to the Equipment entity by ID.
func (wuo *WeaponUpdateOne) SetEquipmentID(id int) *WeaponUpdateOne {
	wuo.mutation.SetEquipmentID(id)
	return wuo
}

// SetNillableEquipmentID sets the "equipment" edge to the Equipment entity by ID if the given value is not nil.
func (wuo *WeaponUpdateOne) SetNillableEquipmentID(id *int) *WeaponUpdateOne {
	if id != nil {
		wuo = wuo.SetEquipmentID(*id)
	}
	return wuo
}

// SetEquipment sets the "equipment" edge to the Equipment entity.
func (wuo *WeaponUpdateOne) SetEquipment(e *Equipment) *WeaponUpdateOne {
	return wuo.SetEquipmentID(e.ID)
}

// SetWeaponRangeID sets the "weapon_range" edge to the WeaponRange entity by ID.
func (wuo *WeaponUpdateOne) SetWeaponRangeID(id int) *WeaponUpdateOne {
	wuo.mutation.SetWeaponRangeID(id)
	return wuo
}

// SetNillableWeaponRangeID sets the "weapon_range" edge to the WeaponRange entity by ID if the given value is not nil.
func (wuo *WeaponUpdateOne) SetNillableWeaponRangeID(id *int) *WeaponUpdateOne {
	if id != nil {
		wuo = wuo.SetWeaponRangeID(*id)
	}
	return wuo
}

// SetWeaponRange sets the "weapon_range" edge to the WeaponRange entity.
func (wuo *WeaponUpdateOne) SetWeaponRange(w *WeaponRange) *WeaponUpdateOne {
	return wuo.SetWeaponRangeID(w.ID)
}

// Mutation returns the WeaponMutation object of the builder.
func (wuo *WeaponUpdateOne) Mutation() *WeaponMutation {
	return wuo.mutation
}

// ClearDamage clears the "damage" edge to the Damage entity.
func (wuo *WeaponUpdateOne) ClearDamage() *WeaponUpdateOne {
	wuo.mutation.ClearDamage()
	return wuo
}

// ClearProperties clears all "properties" edges to the Property entity.
func (wuo *WeaponUpdateOne) ClearProperties() *WeaponUpdateOne {
	wuo.mutation.ClearProperties()
	return wuo
}

// RemovePropertyIDs removes the "properties" edge to Property entities by IDs.
func (wuo *WeaponUpdateOne) RemovePropertyIDs(ids ...int) *WeaponUpdateOne {
	wuo.mutation.RemovePropertyIDs(ids...)
	return wuo
}

// RemoveProperties removes "properties" edges to Property entities.
func (wuo *WeaponUpdateOne) RemoveProperties(p ...*Property) *WeaponUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return wuo.RemovePropertyIDs(ids...)
}

// ClearEquipment clears the "equipment" edge to the Equipment entity.
func (wuo *WeaponUpdateOne) ClearEquipment() *WeaponUpdateOne {
	wuo.mutation.ClearEquipment()
	return wuo
}

// ClearWeaponRange clears the "weapon_range" edge to the WeaponRange entity.
func (wuo *WeaponUpdateOne) ClearWeaponRange() *WeaponUpdateOne {
	wuo.mutation.ClearWeaponRange()
	return wuo
}

// Where appends a list predicates to the WeaponUpdate builder.
func (wuo *WeaponUpdateOne) Where(ps ...predicate.Weapon) *WeaponUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WeaponUpdateOne) Select(field string, fields ...string) *WeaponUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Weapon entity.
func (wuo *WeaponUpdateOne) Save(ctx context.Context) (*Weapon, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WeaponUpdateOne) SaveX(ctx context.Context) *Weapon {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WeaponUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WeaponUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WeaponUpdateOne) check() error {
	if v, ok := wuo.mutation.WeaponCategory(); ok {
		if err := weapon.WeaponCategoryValidator(v); err != nil {
			return &ValidationError{Name: "weapon_category", err: fmt.Errorf(`ent: validator failed for field "Weapon.weapon_category": %w`, err)}
		}
	}
	if v, ok := wuo.mutation.WeaponSubcategory(); ok {
		if err := weapon.WeaponSubcategoryValidator(v); err != nil {
			return &ValidationError{Name: "weapon_subcategory", err: fmt.Errorf(`ent: validator failed for field "Weapon.weapon_subcategory": %w`, err)}
		}
	}
	return nil
}

func (wuo *WeaponUpdateOne) sqlSave(ctx context.Context) (_node *Weapon, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(weapon.Table, weapon.Columns, sqlgraph.NewFieldSpec(weapon.FieldID, field.TypeInt))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Weapon.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, weapon.FieldID)
		for _, f := range fields {
			if !weapon.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != weapon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.WeaponCategory(); ok {
		_spec.SetField(weapon.FieldWeaponCategory, field.TypeEnum, value)
	}
	if value, ok := wuo.mutation.WeaponSubcategory(); ok {
		_spec.SetField(weapon.FieldWeaponSubcategory, field.TypeEnum, value)
	}
	if wuo.mutation.DamageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.DamageTable,
			Columns: []string{weapon.DamageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(damage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.DamageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.DamageTable,
			Columns: []string{weapon.DamageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(damage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   weapon.PropertiesTable,
			Columns: weapon.PropertiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !wuo.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   weapon.PropertiesTable,
			Columns: weapon.PropertiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   weapon.PropertiesTable,
			Columns: weapon.PropertiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.EquipmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.EquipmentTable,
			Columns: []string{weapon.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(equipment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.EquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.EquipmentTable,
			Columns: []string{weapon.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(equipment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.WeaponRangeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.WeaponRangeTable,
			Columns: []string{weapon.WeaponRangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weaponrange.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.WeaponRangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   weapon.WeaponRangeTable,
			Columns: []string{weapon.WeaponRangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weaponrange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Weapon{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{weapon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
