// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ecshreve/dndgen/ent/predicate"
	"github.com/ecshreve/dndgen/ent/weaponrange"
)

// WeaponRangeDelete is the builder for deleting a WeaponRange entity.
type WeaponRangeDelete struct {
	config
	hooks    []Hook
	mutation *WeaponRangeMutation
}

// Where appends a list predicates to the WeaponRangeDelete builder.
func (wrd *WeaponRangeDelete) Where(ps ...predicate.WeaponRange) *WeaponRangeDelete {
	wrd.mutation.Where(ps...)
	return wrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wrd *WeaponRangeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, WeaponRangeMutation](ctx, wrd.sqlExec, wrd.mutation, wrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wrd *WeaponRangeDelete) ExecX(ctx context.Context) int {
	n, err := wrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wrd *WeaponRangeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(weaponrange.Table, sqlgraph.NewFieldSpec(weaponrange.FieldID, field.TypeInt))
	if ps := wrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wrd.mutation.done = true
	return affected, err
}

// WeaponRangeDeleteOne is the builder for deleting a single WeaponRange entity.
type WeaponRangeDeleteOne struct {
	wrd *WeaponRangeDelete
}

// Where appends a list predicates to the WeaponRangeDelete builder.
func (wrdo *WeaponRangeDeleteOne) Where(ps ...predicate.WeaponRange) *WeaponRangeDeleteOne {
	wrdo.wrd.mutation.Where(ps...)
	return wrdo
}

// Exec executes the deletion query.
func (wrdo *WeaponRangeDeleteOne) Exec(ctx context.Context) error {
	n, err := wrdo.wrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{weaponrange.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wrdo *WeaponRangeDeleteOne) ExecX(ctx context.Context) {
	if err := wrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
